### ISSUE TITLE
Virtualbox DKMS

### ISSUE THREAD

**Issue by cromerc** [artix-linux/artools#10]
I can't get virtualbox dkms modules to build during buildiso, this is the output:
```
(1/7) Install DKMS modules
==> dkms install vboxguest/5.1.22_OSE -k 4.9.36-1-lts
Error! Bad return status for module build on kernel: 4.9.36-1-lts (x86_64)
Consult /var/lib/dkms/vboxguest/5.1.22_OSE/build/make.log for more information.
```
Because they can't be built the iso fails to start cinnamon since there are no kernel modules for virtualbox.

**Comment by udeved** [comment]
Yeah, base-devel is not installed in chroot, or else we got the group also on iso.
We may think about doing binary modules?

**Comment by cromerc** [comment]
Maybe base-devel should be included in the chroot? Sometimes dev tools are needed to "repair" a broken system.

**Comment by cromerc** [comment]
Going to close this now that we have vbox modules available for lts.
