### ISSUE TITLE
Branch swith on buildtree

### ISSUE THREAD

**Issue by cromerc** [artix-linux/artools#20]
Is it possible to have buildtree go back the previous selected branch after it pulls?

Last night I used buildtree -ax before I commited and pushed to world. When buildtree finished pulling, it had switched to master and I didn't notice and the push ended up in master instead of artix branch.

**Comment by udeved** [comment]
https://github.com/artix-linux/artools/commit/fb1cead10ac49d03bc9eb1279be83fd509af06b6

**Comment by cromerc** [comment]
This fix works well.
