### ISSUE TITLE
failed rebuilds on jenkins

### ISSUE THREAD

**Issue by udeved** [artix-linux/artools#37]
Hi @thefallenrat 

I got a question, when you rebuilt imagemagick, did you hit the "rebuild" button on server?

I am currently trying to figure out why the linux-ck-nvidia push has 7 commits the jenkins tried to build again.

**Comment by thefallenrat** [comment]
I only rebuild two times. One with a commit, another with a 'rerun' button in the server

**Comment by udeved** [comment]
Which interface did you use on server? Blueocean or default interface?
In the default interface, there is also a replay button, which seems to work better for rebuilds that failed.

I still have no realy clue why we get older commits appended to latest commit, if we did a manual rebuild for failure. It somehow screws up the changelogset object which the pipeline uses.

**Comment by thefallenrat** [comment]
I think it was default interface with circular arrow as a replay button and Jenkins name in the top left of the interface

<a href="https://i.imgur.com/tKVnye0.png">
  <img src="https://imgur.com/tKVnye0l.png" />
</a>

>I still have no realy clue why we get older commits appended to latest commit, if we did a manual rebuild for failure. It somehow screws up the changelogset object which the pipeline uses.

I think it has something to do with how we push the commit? (`git push -f` perhaps?)
I mean we can see here graysky is rewriting the commits 
<a href="https://i.imgur.com/vXNBQIv.png">
  <img src="https://imgur.com/vXNBQIvl.png" />
</a>


Also, I saw qt5-base got appended 8 commits in it 

<a href="https://i.imgur.com/1XajL1b.png">
  <img src="https://imgur.com/1XajL1bl.png" />
</a>

**Comment by udeved** [comment]
qt5-base should not have been committed and pushed.
https://github.com/artix-linux/world/issues/44

The interface used was blueocean.If you hit the exit button, you get to the default interface.
Better don't use this rerun button in blueocean until we figured out what's wrong with the changelogsets.

If you use the replay button in default interface, you get first a view of the pipeline which you can change.
In the stage prepare, it checks if the changelogset size is greater than 0, ie if it has a commit. 
If we push one commit always, ie one pkg, I still don't get how a manual rebuild screws up the changelogset appending all the previous builds from the commit that was rebuilt.

**Comment by thefallenrat** [comment]
So the only best way to rebuild for now is using commit like mine? https://github.com/artix-linux/world/commit/e9052a4ca4963263c877d651a5b62f688a61e7f9

**Comment by udeved** [comment]
Unfortunately, either that, or use the "replay" button in default interface.
"Replay" and "rerun"(rebuild in default iface) seem to produce diffeent changelogsets.
Replay works better, and you can select a commit in the changelogset, you get a editable text view of the pipeline before you can run it with "replay".

**Comment by cromerc** [comment]
Is it possible to disable the rerun button somehow till a fix is found?

**Comment by udeved** [comment]
I don't think so or haven't found a setting to disable it. @cromerc 

I just find it curious behavior, unexpected.
On the other hand, we kind of abuse the thing with basically partial checkouts, parsing changelogsets for the currentbuild object.
With replay, the else statement runs in prepare stage, and it won't parse the objects, but directly query the git history.

**Comment by archnous** [comment]
And I wondered why qt5-base pulled those previous commits... BTW, gstreamer and gst-plugins-base-libs had invalid sigs that stopped the pipeline. Fixed them directly from inside the buildserver.

**Comment by udeved** [comment]
What I propose, we add a few dummy builds to the pipeline-playground git repo, and simply deliberately try to reproduce rebuilds to get to the bottom of the very annoying behavior.

**Comment by archnous** [comment]
The qt5-base commit pulled all previous commits up to failed gst-plugins-base (build #245), same as the nvidia-ck commit. Perhaps a failed job leaves some dirty laundry back?

**Comment by udeved** [comment]
@archnous 

I rebuilt imagemagick manually with replay after I fixed deploypkg.
But why did you push qt5-base?

Dirty laundry shouldn't be present, I recently added workspace checkout dir deletion on success or fail or manual abort, I thought it could perhaps fix this appending of commits to the chagelogset object, but it seems it did not at all. :(

**Comment by archnous** [comment]
I hadn't read https://github.com/artix-linux/world/issues/44
But, since our official kernel is still 4.9, why not build qt5-base anyway? Can't we can remove the no-statx patch and bump once we rebase to 4.14?

**Comment by udeved** [comment]
The arch no-statx patch doesn't effect only qt5-base package, its iirc also qt5-doc and another one or two :(

**Comment by thefallenrat** [comment]
sorry for OT but...

No one here wanna talk about the multilib merge?

I see now that multilib-devel has merge with the core, both lib32-gcc-libs and lib32-glibc is now available in arch's core, thus rendering the package in lib32 useless ....

```
pacman -Sl lib32
lib32 gcc-ada-multilib 7.2.0-3
lib32 gcc-fortran-multilib 7.2.0-3
lib32 gcc-go-multilib 7.2.0-3
lib32 gcc-libs-multilib 7.2.0-3
lib32 gcc-multilib 7.2.0-3
lib32 gcc-objc-multilib 7.2.0-3
lib32 lib32-eudev 3.2.4-2
lib32 lib32-gcc-libs 7.2.0-3 [installed: 7.2.1-2]
lib32 lib32-glibc 2.26-2 [installed: 2.26-8]
```
```
pacman -Sl core | grep lib32
core lib32-gcc-libs 7.2.1-2 [installed]
core lib32-glibc 2.26-8 [installed]
```

Should i introduced them in artix repo?

**Comment by udeved** [comment]
Already done with gcc-7.2.1.
I had removed gcc-7.2.0 from lib32 before I merged it. and our lib32 glibc and gcc-libs are now in system repo.

**Comment by thefallenrat** [comment]
Ahhhh sorry forgot to check it on system repo as well

Carry on

**Comment by udeved** [comment]
https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27workflow-support-plugin%27
https://support.cloudbees.com/hc/en-us/articles/217630098-How-to-access-Changelogs-in-a-Pipeline-Job-
