### ISSUE TITLE
Development goals 2018

### ISSUE THREAD

**Issue by udeved** [artix-linux/artools#38]
Hi @artix-linux/developers,

I start a little list what we may want to achieve in the new year.

Top priority:

- [x] transfer all packages in their own repos
- [x] use git subtree in packages super repo
- [x] make pipeline work with subtree
- [x] make artools-pkg work with subtree
- [ ] implement a notification system in pipeline which informs us of failed builds
- [x] figure out what is wrong with the server and big packages, take a look at the kernel.log on server, scary

Please append the list.
I wish a happy new year.

**Comment by udeved** [comment]
@cromerc 

What do you think about git subtree?

https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree

Sounds more like our use case.
git submodules als don't play nice atm with the jenkins GH plugin.

**Comment by udeved** [comment]
Its what I want to find out, but I think it would work, because you basically have no symlinks within the master repo, but true nested repos. A clone or pull would do the entire thing, no additional submodule inits or so, afaik. I think, this is how the AUR works eventually, with subtree.
The GH plugin we use doesn't currently support submodules, and we would have to switch to using the default git plugin losing GH some integration.

**Comment by DamnWidget** [comment]
But you still need to create a single repository for each one of the
packages, even if in the user machine ( jenkins copy of the repo in this
case) everything looks like the same. I am not sure how the subtrees helps
with our problem, probably because I don't really understand what the
problem is.

**Comment by udeved** [comment]
The problem is that we need one repo for each package and isolated per repo commits.
With subtree, afaik, we could have a master repo, and simply add the single package repos from our artix-packages GH org.
The master repo would look like a normal repo, with all packages in it, but these would be nested, no links as with submodules.
With submodules, we would have a master repo containing commit links to the submodule repos.
Simplified, subtree is like copy, submodules are symlinks.

**Comment by udeved** [comment]
@cromerc 

I have an almost working transition script that creates for each package a repo on artix-packages and pushes the package.

**Comment by udeved** [comment]
```
#!/bin/bash

# alias git=hub

super_repo=/home/artux/artools-workspace/artix/packages

copy_pkgs(){
    for repo in system world;do
        local old_repo=/home/artux/artools-workspace/artix/$repo
        cd $old_repo
        local packages=$(find . -mindepth 1 -maxdepth 1 -type d)
       # git checkout testing
        for p in ${packages[@]};do
            local pkg=${p#*/}             
            mkdir -p $super_repo/$pkg/$repo
        #     cp -v $pkg/* $super_repo/$pkg/trunk/
            cp -v $pkg/* $super_repo/$pkg/$repo/
        done
    done
    rm -r $super_repo/.git
}

create_pkg_repo(){
    cd $super_repo
    local packages=$(find . -mindepth 1 -maxdepth 1 -type d)
    for p in ${packages[@]};do
        local pkg=${p#*/} 
        cd $pkg
        git init
        git add .
        git commit -m "initial commit $pkg"
        hub create artix-packages/$pkg
        git push origin master
        cd ..
    done
}

copy_pkgs
create_pkg_repo
```

**Comment by udeved** [comment]
https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository

**Comment by udeved** [comment]
@artix-linux/developers 

I figured git subtree to be not suitable as well.
git subrepo sounds more useful for the task.

https://github.com/ingydotnet/git-subrepo

Anyway, I made some pipeline changes in playground which matches the arch svn repo structure, ie we would move packages within the package folder from testing to $repo.
I propose as intermediate step, that we switch over to basically arch structure in git, regardless what git extension we chose.

**Comment by udeved** [comment]
@cromerc @archnous @graysky2 @thefallenrat @konimex 

I would like to plan a mini meeting on irc to coordinate a time table for the repo switch with you guys.

**Comment by cromerc** [comment]
If not today, I will be out of town until the 31st  of January.

**Comment by udeved** [comment]
I would be fine with today/tonight. 
Its just that we all have to start new repos at once, and a few words on the new structure may be necessary to get the new workflow going.

**Comment by cromerc** [comment]
I wasn't able to get on, we are preparing for our trip. Please fill me in on the details for when I get back.

**Comment by DamnWidget** [comment]
I just read this now :(

**Comment by udeved** [comment]
@artix-linux/developers @artix-linux/packages @artix-linux/packages-galaxy 

* Draft

### Maintainers

The packages git follows the archlinux svn structure.
It contains both core and extra PKGBUILD

Each package folder consists of a trunk and repos directory
The package will always be updated in trunk, and then based on trunk action taken in the repos directory.

To sync the arch and artix git repos, run

    buildtree -s

To import from archlinux, run

    buildtree -i


To compare arch and artix repo versions, run

    buildtree -c

It will show a version comparison table between arch repos and artix repos.
The first repository column shows the archlinux repos the package is in.

In order to manage packages in the git tree, commitpkg standardizes the actions with descriptive commit messages.

~~~
$ commitpkg -h
Usage: commitpkg [options]
    -g                 Git repository [default:packages]
    -r                 Repository [default:core]
    -p                 Package name [default:]
    -z                 Move package to staging repo
    -y                 Move package to testing repo
    -x                 Move package to repo
    -n                 New repo package from trunk
    -u                 Push
    -q                 Query settings and pretend
    -h                 This help
~~~

* Example 1

A new package foo has been added foo/trunk/PKGBUILD

add copy of trunk to repos/staging-x86_64

    commitpkg -p foo -r staging -n

move foo from repos/staging-x86_64 to repos/testing-x86_64

    commitpkg -p foo -r staging -y

move foo from repos/testing-x86_64 to repos/core-x86_64

    commitpkg -p foo -r core -x

If foo should be moved from repos/testing-x86_64 to repos/staging-x86_64, run

    commitpkg -p foo -r testing -z


* Example 2

add copy of trunk of package foo2 to repos/testing-any and push

    commitpkg -p foo2 -r testing -nu

move foo2 from repos/testing-any to repos/extra-any

    commitpkg -p foo2 -r extra -xu


##### The jenkins pipeline will not trigger any action on the server, if only trunk has been modified, commited and pushed.

* Jenkinsfile stages
    * Checkout
    * Build
    * Add
    * Remove

* Any repo moving operation of a package in git will trigger Add and Remove stages.
* Any new repos subdirectory will trigger the Build stage.
