### ISSUE TITLE
Failure with multilib

### ISSUE THREAD

**Issue by cromerc** [artix-linux/artools#47]
https://github.com/artix-linux/packages-galaxy/commit/bde833354fe4f9814a319ae794c6db1770f7df84

For some reason it is creating a trunk folder in the repo folder which causes failure to build.

**Comment by udeved** [comment]
What tools version do ou have installed? git or repo version?
Repo version 0.7.2 should have this fixed. Please test.

**Comment by cromerc** [comment]
I have 0.7.2
This issue with it making a "trunk" folder inside the repo folder only happens with "multilibpkg" it does not happen with "multilib-testingpkg", so there is something different in these 2.

Also there appears to be a problem with the build server for lib32 builds:
`==> ERROR: '/var/lib/artools/buildpkg/lib32-x86_64/root' does not appear to be an artix chroot.`

**Comment by cromerc** [comment]
Also from what I remember, a separate lib32 chroot should not be necessary anymore since gcc-multilib was removed and everything moved into gcc and lib32-gcc-lib. Or am I incorrect in thinking this?

**Comment by udeved** [comment]
We had multiple issues at once here.
There was a borked lib32 chroot on server. Fixed.
The lib32 repo db was outdated and had old gcc. Fixed.

lib32-dbus built fine.

Why commitpkg produced strangeness, I dunno, but I think you bumped version and this caused it.
Why did you bump to 1.1, 1.2 or 1.3 if simply removing a header comment in the repo folder is sufficient to keep trunk version after build failed?

**Comment by cromerc** [comment]
Well at least that part is fixed, why the strangeness, no clue here. If it happens again I will reopen this.
