### ISSUE TITLE
buildiso has problem with package signatures

### ISSUE THREAD

**Issue by SGOrava** [artix-linux/artools#55]
Hello,
I went by the [wiki](https://wiki.artixlinux.org/Main/InstallationUsingBuildiso) and started to play with buildiso.

I use this command to start buildiso:

    buildiso  -r /home/juraj/artools/buildiso -p lxqt -k linux-lts -i openrc

When pacman is installing packages in chroot (by buildiso) for the first time it show error on multiple packages and build fails.

    signature from "Artix Buildbot <buildbot@artixlinux.org>" is invalid

When the buildiso is started again all packages are recognized as good and i am able to continue with my journey until pacman is started for another fs (rootfs, livefs, desktopfs) and this error repeat itself.

Full log:
https://gist.github.com/SGOrava/8408b9e3218f020505ef778e9517c0bb

**Comment by udeved** [comment]
You should clean your pacman cache.
I have added many packages recently that failed building when we initially had added them.

**Comment by SGOrava** [comment]
Thank you for your help.
Information was added to the wiki.
