### ISSUE TITLE
install media

### ISSUE THREAD

**Issue by udeved** [artix-linux/artools#6]
I successfully built yesterday first install test media.
All fine so far, fine tuning of calamares now.

@cromerc 

If you want, create a lxde profile and presets too.

**Comment by cromerc** [comment]
I am going to do a cinnamon profile since that is what I use.

**Comment by cromerc** [comment]
Trying to use buildiso and am getting this:
```
==> Start building [lxqt]
==> Removing chroot copy [/var/lib/artools/buildiso/lxqt/x86_64/rootfs]...done
==> Deleting isoroot [iso] ...
 --> Loading Packages: [] ...
sed: can't read : No such file or directory
==> Prepare [Base installation] (rootfs)
==> ERROR: You must specify a directory and one or more packages.
==> ERROR: A failure occurred in make_image_root().
    Aborting...
```

I am using the command:
`buildiso -p cinnamon`
